version: '3'

services:
  consul:
    hostname: consul
    image: consul
    ports:
      - 8500:8500 # Consul HTTP
      - 53
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'true'
      CONSUL_LOCAL_CONFIG: '{ "ports": { "dns": 53 }, "recursors": [ "8.8.8.8" ] }'
    volumes:
      - ./volumes/consul:/consul/data:rw
    networks:
      default:
        ipv4_address: ${CONSUL_IP:-172.22.0.100}

  puppet:
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    environment:
      # DNS_ALT_NAMES must be set before starting the stack the first time,
      # and must list all the names under which the puppetserver can be
      # reached. 'puppet' must be one of them, otherwise puppetdb won't be
      # able to get a cert. Add other names as a comma-separated list
      - DNS_ALT_NAMES=puppet,puppet.service.consul,${DNS_ALT_NAMES:-}
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      - CONSUL_ENABLED=true
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    depends_on:
      - consul
    dns:
      - ${CONSUL_IP:-172.22.0.100}
      # need to add this to work around https://github.com/moby/moby/issues/38932
      # for windows
      - 127.0.0.11
    volumes:
      - ${VOLUME_ROOT:-.}/volumes/code:/etc/puppetlabs/code/
      - ${VOLUME_ROOT:-.}/volumes/puppet:/etc/puppetlabs/puppet/
      - ${VOLUME_ROOT:-.}/volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/
    networks:
      default:
        aliases:
         - puppet.${AZURE_DOMAIN:-}

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432
    volumes:
      - ${VOLUME_ROOT:-.}/volumes/puppetdb-postgres/data:/var/lib/postgresql/data
      - ./postgres-custom:/docker-entrypoint-initdb.d

  puppetdb:
    hostname: puppetdb
    image: underscorgan/puppetdb:6.3.2
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      # This name is an FQDN so the short name puppet doesn't collide outside compose network
      - PUPPETSERVER_HOSTNAME=puppet.${AZURE_DOMAIN:-}
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - CONSUL_ENABLED=true
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres
      - puppet
    dns:
      - ${CONSUL_IP:-172.22.0.100}
      # need to add this to work around https://github.com/moby/moby/issues/38932
      # for windows
      - 127.0.0.11
    volumes:
      - ${VOLUME_ROOT:-.}/volumes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

networks:
  default:
    ipam:
      config:
        - subnet: ${PUPPERWARE_SUBNET:-172.22.0.0/16}
